#server:
#  port: 8080
#  address: 0.0.0.0
#  servlet:
#    context-path: /api    #应用的上下文路径，详细参考 云枢帮助中心-开发者手册-解决跨域安全问题
#
#spring:
#  #mysql
#  datasource:
#    username: root
#    password: Passw0rd
#    url: jdbc:mysql://172.16.77.183:3306/cloudpivot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    driver-class-name: com.mysql.jdbc.Driver
#  #redis
#  redis:
#    host: 127.0.0.1     #地址
#    database: 1         #集群模式下不指定数据库，注释此选项
#    password: foobared  #密码
#    port: 6379          #端口
#    ## 集群模式
#    #cluster:
#    #  nodes:   # cluster节点地址
#    #    - "127.0.0.1:6379"
#    #    - "127.0.0.1:6389"
#    #    - "127.0.0.1:6399"
#    ## 哨兵模式
#    #sentinel:
#    #  nodes:   # 哨兵节点地址
#    #    - "127.0.0.1:26379"
#    #    - "127.0.0.1:26389"
#    #    - "127.0.0.1:26399"
#    #  master: mymaster    # 主服务器的名称
#
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 200MB         #上传单个文件大小限制
#      max-request-size: 200MB      #多个同时上传总大小限制
#
#mybatis:
#  mapper-locations: classpath:mapping/*Mapping.xml
#  type-aliases-package: com.authine.cloudpivot.mybatis.entity
#
#logging:
#  level:
#    com.authine.cloudpivot: info   # 云枢产品日志输出级别
#
## logback日志配置
#log:
#  path: logs           #日志文件输出路径，默认为应用所在目录的logs目录
#  maxFileSize: 50MB    #单个日志文件大小，默认50MB
#  maxHistory: 45       #默认保存45天的记录
#  totalLogSizeCap: 20GB #总日志文件上限大小，默认20GB，当日志大小超过这个值，删除旧的日志
#  errorLogSizeCap: 5GB  #错误日志文件上限大小，默认5GB，当日志大小超过这个值，删除旧的日志
#
#dubbo:
#  registry:
#    protocol: zookeeper
#    address: 127.0.0.1  #服务注册地址
#    port: 2181          #端口
#    timeout: 3000       #超时时间
#    check: true
#  consumer:
#    check: false
#    retries: 0          #重试次数
#
#cloudpivot:
#  login:
#    dingtalk: false #钉钉方式登录
#    accountpassword: false #账号密码登录
#    dingtalk&accountpassword: true #钉钉扫码和账号密码方式登录
#  switch:
#    multi_language_toggle_switch: false  #多语言开关 默认关
#  attachment:   # 文件存储方式
#    oss:
#      enabled: true     #是否启用
#    sftp:
#      enabled: false      #是否启用
#  bizlog:
#    endpoint:        #地域节点 如：oss-cn-shenzhen.aliyuncs.com
#    accessKeyId:     #用户AccessKey
#    accessKeySecret: #Access Key Secret
#    project:     #SLS项目名称
#    logStore: webapi_log    #web-sso日志库


server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api    #应用的上下文路径，详细参考 云枢帮助中心-开发者手册-解决跨域安全问题

spring:
  #mysql
  datasource:
    username: root
    password: Passw0rd
    url: jdbc:mysql://172.16.77.181:3306/cloudpivot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  #redis
  redis:
    host: 172.16.77.181  #地址
    database: 1         #
    password: foobared  #密码
    port: 6379          #端口
    # 集群模式
    #cluster:
    #  nodes:   # cluster节点地址
    #    - "172.18.14.235:6379"
    #    - "172.18.14.235:6389"
    #    - "172.18.14.235:6399"
    # 哨兵模式
    #sentinel:
    #  nodes:   # 哨兵节点地址
    #    - "172.18.14.235:26379"
    #    - "172.18.14.235:26389"
    #    - "172.18.14.235:26399"
    #  master: mymaster    # 主服务器的名称

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB         #上传单个文件大小限制
      max-request-size: 200MB      #多个同时上传总大小限制
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.authine.cloudpivot.mybatis.entity

logging:
  level:
    com.authine.cloudpivot: debug   # 云枢产品日志输出级别

dubbo:
  registry:
    protocol: zookeeper
    address: 127.0.0.1  #服务注册地址
    port: 2181          #端口
    timeout: 3000       #超时时间
    check: true
  consumer:
    check: false
    retries: 0          #重试次数

cloudpivot:
  login:
    dingtalk: false #钉钉方式登录
    accountpassword: false #账号密码登录
    dingtalk&accountpassword: true #钉钉扫码和账号密码方式登录
  switch:
    multi_language_toggle_switch: false  #多语言开关 默认关
  attachment:   # 文件存储方式
    oss:
      enabled: true     #是否启用
    sftp:
      enabled: false     #是否启用
  api:
    oauth:
      enabled: true   # 是否开启权限校验
      test:
        userid: afeb204e71a9d3050171a9d464e60001      # 模拟测试用户ID，不能用于生产环境
  bizlog:
    endpoint:        #地域节点 如：oss-cn-shenzhen.aliyuncs.com
    accessKeyId:     #用户AccessKey
    accessKeySecret: #Access Key Secret
    project:     #SLS项目名称
    logStore: webapi_log    #web-sso日志库
  report:
    datasourceurl: http://127.0.0.1